function hUI = dashboard(cfg)
% DASHBOARD Interactive MATLAB GUI Dashboard for SIH26037 Autonomous Vehicle.
%
% Creates a dual-panel tactical display featuring:
%   - Left/Top: High-resolution Bird's-Eye-View (BEV) road scene & live path tracking
%   - Right/Top: Real-time Vehicle Dynamics & Speedometer metrics
%   - Bottom: Tactical Risk Assessment Banner (SAFE / WARNING / CRITICAL),
%             TTC Gauge, Nearest Obstacle Telemetry, and Interactive Scenario Controls.
%
% Inputs:
%   cfg - System configuration struct (optional)
%
% Output:
%   hUI - Struct containing handles to figure, axes, telemetry labels, and buttons.

    if nargin < 1 || isempty(cfg), cfg = config(); end

    % Close existing instance if open
    existingFig = findobj('Type', 'figure', 'Name', 'Smart Autonomous Vehicle - SIH26037');
    if ~isempty(existingFig)
        close(existingFig);
    end

    % Main Figure Window
    fig = figure(...
        'Name', 'Smart Autonomous Vehicle - SIH26037', ...
        'NumberTitle', 'off', ...
        'Color', cfg.ui.bgDark, ...
        'Position', [80, 80, 1280, 760], ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'DockControls', 'off');

    hUI = struct();
    hUI.fig = fig;
    hUI.cfg = cfg;
    hUI.isPaused = false;
    hUI.isRunning = false;
    hUI.selectedScenario = 3; % Cattle Crossing default
    hUI.stepRequested = false;

    %% 1. Header Banner
    uicontrol('Parent', fig, 'Style', 'text', ...
        'String', 'SIH26037: Smart Autonomous Vehicle — Adaptive Indian Road Navigation', ...
        'Units', 'normalized', 'Position', [0.02, 0.94, 0.96, 0.05], ...
        'BackgroundColor', [0.06, 0.08, 0.10], 'ForegroundColor', [0.0, 0.85, 1.0], ...
        'FontWeight', 'bold', 'FontSize', 14, 'HorizontalAlignment', 'center');

    %% 2. Main Simulation Map Axes (Left Panel)
    axMap = axes('Parent', fig, ...
        'Units', 'normalized', 'Position', [0.03, 0.28, 0.68, 0.64], ...
        'Color', cfg.ui.bgDark);
    hUI.axMap = axMap;

    %% 3. Right Telemetry & Status Panel
    pnlRight = uipanel('Parent', fig, 'Title', 'VEHICLE TELEMETRY', ...
        'Units', 'normalized', 'Position', [0.73, 0.28, 0.25, 0.64], ...
        'BackgroundColor', [0.14, 0.16, 0.20], 'ForegroundColor', [0.9, 0.9, 0.9], ...
        'FontWeight', 'bold', 'FontSize', 11);

    % Speedometer Label
    uicontrol('Parent', pnlRight, 'Style', 'text', 'String', 'VEHICLE SPEED', ...
        'Units', 'normalized', 'Position', [0.05, 0.86, 0.90, 0.06], ...
        'BackgroundColor', [0.14, 0.16, 0.20], 'ForegroundColor', [0.7, 0.7, 0.7], ...
        'FontSize', 9, 'FontWeight', 'bold');

    hUI.lblSpeed = uicontrol('Parent', pnlRight, 'Style', 'text', ...
        'String', '0.0 km/h (0.0 m/s)', ...
        'Units', 'normalized', 'Position', [0.05, 0.78, 0.90, 0.08], ...
        'BackgroundColor', [0.08, 0.10, 0.13], 'ForegroundColor', [0.0, 0.85, 1.0], ...
        'FontSize', 13, 'FontWeight', 'bold');

    % Steering Angle Label
    uicontrol('Parent', pnlRight, 'Style', 'text', 'String', 'STEERING ANGLE', ...
        'Units', 'normalized', 'Position', [0.05, 0.68, 0.90, 0.06], ...
        'BackgroundColor', [0.14, 0.16, 0.20], 'ForegroundColor', [0.7, 0.7, 0.7], ...
        'FontSize', 9, 'FontWeight', 'bold');

    hUI.lblSteer = uicontrol('Parent', pnlRight, 'Style', 'text', ...
        'String', '0.0 deg (0.00 rad)', ...
        'Units', 'normalized', 'Position', [0.05, 0.60, 0.90, 0.08], ...
        'BackgroundColor', [0.08, 0.10, 0.13], 'ForegroundColor', [1.0, 0.8, 0.2], ...
        'FontSize', 12, 'FontWeight', 'bold');

    % Nearest Obstacle Distance
    uicontrol('Parent', pnlRight, 'Style', 'text', 'String', 'NEAREST OBSTACLE', ...
        'Units', 'normalized', 'Position', [0.05, 0.50, 0.90, 0.06], ...
        'BackgroundColor', [0.14, 0.16, 0.20], 'ForegroundColor', [0.7, 0.7, 0.7], ...
        'FontSize', 9, 'FontWeight', 'bold');

    hUI.lblObstacle = uicontrol('Parent', pnlRight, 'Style', 'text', ...
        'String', 'None Detected (>40m)', ...
        'Units', 'normalized', 'Position', [0.05, 0.42, 0.90, 0.08], ...
        'BackgroundColor', [0.08, 0.10, 0.13], 'ForegroundColor', [0.95, 0.60, 0.10], ...
        'FontSize', 11, 'FontWeight', 'bold');

    % Replanning Count & Algorithm
    uicontrol('Parent', pnlRight, 'Style', 'text', 'String', 'PLANNER STATUS', ...
        'Units', 'normalized', 'Position', [0.05, 0.32, 0.90, 0.06], ...
        'BackgroundColor', [0.14, 0.16, 0.20], 'ForegroundColor', [0.7, 0.7, 0.7], ...
        'FontSize', 9, 'FontWeight', 'bold');

    hUI.lblPlanner = uicontrol('Parent', pnlRight, 'Style', 'text', ...
        'String', 'Adaptive A* (0 Replans)', ...
        'Units', 'normalized', 'Position', [0.05, 0.24, 0.90, 0.08], ...
        'BackgroundColor', [0.08, 0.10, 0.13], 'ForegroundColor', [0.15, 0.90, 0.35], ...
        'FontSize', 11, 'FontWeight', 'bold');

    % Simulation Time & Progress
    hUI.lblTime = uicontrol('Parent', pnlRight, 'Style', 'text', ...
        'String', 'Time: 0.00s | Progress: 0%', ...
        'Units', 'normalized', 'Position', [0.05, 0.08, 0.90, 0.12], ...
        'BackgroundColor', [0.08, 0.10, 0.13], 'ForegroundColor', [0.8, 0.8, 0.8], ...
        'FontSize', 10, 'FontWeight', 'bold');

    %% 4. Bottom Tactical Risk & Control Panel
    pnlBottom = uipanel('Parent', fig, 'Title', 'COLLISION RISK ASSESSMENT & CONTROLS', ...
        'Units', 'normalized', 'Position', [0.03, 0.02, 0.95, 0.23], ...
        'BackgroundColor', [0.14, 0.16, 0.20], 'ForegroundColor', [0.9, 0.9, 0.9], ...
        'FontWeight', 'bold', 'FontSize', 11);

    % Risk State Big Banner
    hUI.pnlRisk = uicontrol('Parent', pnlBottom, 'Style', 'text', ...
        'String', 'RISK: SAFE', ...
        'Units', 'normalized', 'Position', [0.02, 0.45, 0.26, 0.45], ...
        'BackgroundColor', cfg.ui.colorSafe, 'ForegroundColor', [0.05, 0.15, 0.05], ...
        'FontSize', 18, 'FontWeight', 'bold');

    % Risk Explanation Reason
    hUI.lblReason = uicontrol('Parent', pnlBottom, 'Style', 'text', ...
        'String', 'Reason: Road ahead is clear. Cruise tracking active.', ...
        'Units', 'normalized', 'Position', [0.02, 0.08, 0.26, 0.32], ...
        'BackgroundColor', [0.08, 0.10, 0.13], 'ForegroundColor', [0.9, 0.9, 0.9], ...
        'FontSize', 9, 'HorizontalAlignment', 'left');

    % Scenario Selector Dropdown
    uicontrol('Parent', pnlBottom, 'Style', 'text', 'String', 'Select Scenario:', ...
        'Units', 'normalized', 'Position', [0.31, 0.65, 0.20, 0.25], ...
        'BackgroundColor', [0.14, 0.16, 0.20], 'ForegroundColor', [0.8, 0.8, 0.8], ...
        'FontSize', 9, 'FontWeight', 'bold', 'HorizontalAlignment', 'left');

    scenarioNames = {
        '1: Narrow Rural Road', ...
        '2: Potholes on Path', ...
        '3: Cattle Crossing (SIH Demo)', ...
        '4: Pedestrian Crossing', ...
        '5: Auto-Rickshaw Obstruction', ...
        '6: Unsignalized Intersection', ...
        '7: Chaotic Mixed Traffic'
    };

    hUI.popScenario = uicontrol('Parent', pnlBottom, 'Style', 'popupmenu', ...
        'String', scenarioNames, 'Value', 3, ...
        'Units', 'normalized', 'Position', [0.31, 0.25, 0.22, 0.35], ...
        'BackgroundColor', [0.22, 0.24, 0.28], 'ForegroundColor', [1 1 1], ...
        'FontSize', 10, 'FontWeight', 'bold');

    % Control Buttons: [Start / Resume], [Pause], [Reset], [Step]
    hUI.btnStart = uicontrol('Parent', pnlBottom, 'Style', 'pushbutton', ...
        'String', 'Start Demo', ...
        'Units', 'normalized', 'Position', [0.56, 0.22, 0.12, 0.58], ...
        'BackgroundColor', [0.10, 0.65, 0.30], 'ForegroundColor', [1 1 1], ...
        'FontSize', 11, 'FontWeight', 'bold');

    hUI.btnPause = uicontrol('Parent', pnlBottom, 'Style', 'pushbutton', ...
        'String', 'Pause', ...
        'Units', 'normalized', 'Position', [0.70, 0.22, 0.10, 0.58], ...
        'BackgroundColor', [0.80, 0.55, 0.10], 'ForegroundColor', [1 1 1], ...
        'FontSize', 11, 'FontWeight', 'bold');

    hUI.btnReset = uicontrol('Parent', pnlBottom, 'Style', 'pushbutton', ...
        'String', 'Reset', ...
        'Units', 'normalized', 'Position', [0.82, 0.22, 0.08, 0.58], ...
        'BackgroundColor', [0.75, 0.20, 0.20], 'ForegroundColor', [1 1 1], ...
        'FontSize', 11, 'FontWeight', 'bold');

    hUI.btnStep = uicontrol('Parent', pnlBottom, 'Style', 'pushbutton', ...
        'String', 'Step >', ...
        'Units', 'normalized', 'Position', [0.91, 0.22, 0.07, 0.58], ...
        'BackgroundColor', [0.25, 0.45, 0.70], 'ForegroundColor', [1 1 1], ...
        'FontSize', 11, 'FontWeight', 'bold');
end
